### ISSUE TITLE
TextAttributeKey(name:'SIMPLE_BAD_CHARACTER', defaultAttributes:'null')  was already registered

### ISSUE THREAD

**Issue by maksimu** [adelf/idea-php-dotenv-plugin#33]
IntelliJ Version:

```
IntelliJ IDEA 2018.3.3 (Ultimate Edition)
Build #IU-183.5153.38, built on January 9, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
```

Got following error when opened IntelliJ:

```
java.lang.IllegalStateException: TextAttributeKey(name:'SIMPLE_BAD_CHARACTER', defaultAttributes:'null')  was already registered with the other defaultAttributes: [java.awt.Color[r=255,g=100,b=100],null,1,null,null,null]
	at com.intellij.openapi.editor.colors.TextAttributesKey.mergeKeys(TextAttributesKey.java:220)
	at com.intellij.openapi.editor.colors.TextAttributesKey.lambda$getOrCreate$4(TextAttributesKey.java:200)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
	at com.intellij.openapi.editor.colors.TextAttributesKey.getOrCreate(TextAttributesKey.java:200)
	at com.intellij.openapi.editor.colors.TextAttributesKey.createTextAttributesKey(TextAttributesKey.java:187)
	at ru.adelf.idea.dotenv.DotEnvSyntaxHighlighter.<clinit>(DotEnvSyntaxHighlighter.java:25)
	at ru.adelf.idea.dotenv.DotEnvSyntaxHighlighterFactory.getSyntaxHighlighter(DotEnvSyntaxHighlighterFactory.java:12)
	at com.intellij.openapi.fileTypes.SyntaxHighlighterFactory.getSyntaxHighlighter(SyntaxHighlighterFactory.java:39)
	at org.jetbrains.plugins.ruby.ruby.lang.highlighter.RubyEditorHighlighter.<init>(RubyEditorHighlighter.java:44)
	at org.jetbrains.plugins.ruby.ruby.lang.highlighter.RubyEditorHighlighterProvider.getEditorHighlighter(RubyEditorHighlighterProvider.java:18)
	at com.intellij.openapi.editor.highlighter.EditorHighlighterFactoryImpl.createEditorHighlighter(EditorHighlighterFactoryImpl.java:78)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.loadEditorInBackground(TextEditorImpl.java:75)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground(PsiAwareTextEditorImpl.java:51)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$tryLoadEditor$3(AsyncEditorLoader.java:162)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$4(PsiDocumentManagerBase.java:491)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:977)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:489)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$tryLoadEditor$4(AsyncEditorLoader.java:167)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:123)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.tryLoadEditor(AsyncEditorLoader.java:166)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$scheduleLoading$2(AsyncEditorLoader.java:120)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:200)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

![image](https://user-images.githubusercontent.com/187306/51558107-811f7a80-1e33-11e9-9c95-95601ac4993a.png)

**Comment by adelf** [comment]
Thanks. Will be fixed soon.
