### ISSUE TITLE
SOE in zipdata.go

### ISSUE THREAD

**Issue by artspb** [adelf/idea-php-dotenv-plugin#75]
The issue is reported by one of the IDEA users against build 211.4961.33.

```
Error while indexing /usr/local/Cellar/go/1.15.3/libexec/src/time/tzdata/zipdata.go
To reindex this file IDEA has to be restarted

java.lang.StackOverflowError
	at com.goide.GoTypes$Factory.createElement(GoTypes.java:209)
	at com.goide.GoParserDefinition.createElement(GoParserDefinition.java:109)
	at com.intellij.psi.impl.source.tree.CompositeElement.createPsiNoLock(CompositeElement.java:705)
	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:692)
	at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:16)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:37)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getFirstChild(ASTDelegatePsiElement.java:99)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:67)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
	at ru.adelf.idea.dotenv.go.GoEnvironmentCallsVisitor.visitElement(GoEnvironmentCallsVisitor.java:22)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at com.goide.psi.impl.GoExpressionImpl.accept(GoExpressionImpl.java:27)
	at com.goide.psi.impl.GoBinaryExprImpl.accept(GoBinaryExprImpl.java:26)
	at com.goide.psi.impl.GoAddExprImpl.accept(GoAddExprImpl.java:26)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
<removed>
	at ru.adelf.idea.dotenv.go.GoEnvironmentCallsVisitor.visitElement(GoEnvironmentCallsVisitor.java:22)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at com.goide.psi.impl.GoExpressionImpl.accept(GoExpressionImpl.java:27)
	at com.goide.psi.impl.GoBinaryExprImpl.accept(GoBinaryExprImpl.java:26)
	at com.goide.psi.impl.GoAddExprImpl.accept(GoAddExprImpl.java:26)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
	at ru.adelf.idea.dotenv.go.GoEnvironmentCallsVisitor.visitElement(GoEnvironmentCallsVisitor.java:22)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at com.goide.psi.impl.GoExpressionImpl.accept(GoExpressionImpl.java:27)
	at com.goide.psi.impl.GoBinaryExprImpl.accept(GoBinaryExprImpl.java:26)
	at com.goide.psi.impl.GoAddExprImpl.accept(GoAddExprImpl.java:26)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
```

**Comment by adelf** [comment]
Hi, Artem. Seems, this user uses a very old version of the ".env file support" plugin. v0.7 I think.
The plugin doesn't index go files since 2019.* versions.

**Comment by artspb** [comment]
I see that there's still https://github.com/adelf/idea-php-dotenv-plugin/blob/master/src/main/java/ru/adelf/idea/dotenv/go/GoEnvironmentCallsVisitor.java. That's why I've created this issue. If the file isn't used then you can disregard the ticket. I just wanted to let you know that such an exception was reported.

**Comment by adelf** [comment]
Yes. There were SOE issues for big files when this visitor wasn't "walking". But after making it "walking" and removing indexing from all non-.env files, the issue has been disappeared. Thank you anyway.
